import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aiSkillSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
